### ISSUE TITLE
How to render content in front of the cards?

### ISSUE THREAD

**Issue by zholmes1** [tarasvakulka/react-native-cards-swipe#3]
I want to have some floating buttons rendered in front of the cards. Unfortunately they only show after I swipe the first card away. I can provide a video if you don't understand what I mean.

**Comment by tarasvakulka** [comment]
Provide a video, please. Also would be a great, if you  provide reproducible example.

**Comment by zholmes1** [comment]
Here's a video: https://drive.google.com/file/d/11-8Ij2LySF0YOJanO3p8nQohuJZbyOfB/view?usp=sharing

You'll notice that the absolute positioned components only appear after I swipe away the first card. After the first one is swiped away, everything is fixed.

```
    <View style={{ flex: 1, backgroundColor: 'black' }}>
      <Swiper
        ref={swiperRef}
        loop={false}
        cards={users}
        onSwiped={index => {
          // removed code
        }}
        renderCard={(user: FirestoreUser) => {
         // removed code
        }}
        renderNoMoreCard={() => {
          // removed code
        }}
      />
      <View
        style={{
          position: 'absolute',
          top: 56,
          right: 16,
          zIndex: 5000
        }}
      >
        <FilterButton/>
      </View>
      <View
        style={{
          position: 'absolute',
          bottom: 122,
          right: 16
        }}
      >
        <QuestionButton />
      </View>
      <View style={{ position: 'absolute', bottom: 122, left: 16 }}>
        <HeartButton />
      </View>
    </View>
```

**Comment by tarasvakulka** [comment]
Could you please try to add elevation: 101 to you floating button wrapper (View with zIndex: 5000)  ?

**Comment by zholmes1** [comment]
Perfect! I was able to remove the zIndex as well.

**Comment by zholmes1** [comment]
I just remembered that elevation is for Android only. What should we do about iOS?

**Comment by tarasvakulka** [comment]
> I just remembered that elevation is for Android only. What should we do about iOS?

Yes, elevation is only for android, for IOS just keep zIndex. Also I think elavation: 3 should be enough

**Comment by zholmes1** [comment]
Okay I'm testing zIndex on iOS now

**Comment by zholmes1** [comment]
iOS didn't even need zIndex. Just the fact that they are rendered after the Swiper in the component tree is good enough.
