### ISSUE TITLE
The onSwipeStart callback has no information about where the user is swiping

### ISSUE THREAD

**Issue by moleinik** [tarasvakulka/react-native-cards-swipe#5]
I ran into a problem with `onSwipeStart`. Сallback doesn't have any data about the card swipe direction. We can get only index and that's all.
Can we get more additional information about cards in callbacks (onSwipeStart, onSwipeEnd)?

**Comment by tarasvakulka** [comment]
Probably yes, PRs are welcome) For now I'm quite busy and can't estimate correctly when I can implement this feature, but I can ping you when this will be ready.

**Comment by moleinik** [comment]
Nice) I will create a merge request after the weekend. Thank you for your response, @tarasvakulka. I think that this issue is not relevant from now on. I will close it.
